spring:

  # Swagger springdoc-ui Configuration
  springdoc:
    packages-to-scan: com.adjh.springboot3tierform
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    cache:
      disabled: true              # 캐시 사용 여부
    api-docs:
      path: /api-docs/json
      groups:
        enabled: true
    swagger-ui:
      enabled: true               # Swagger UI 사용여부 : 접근 경로 => <http://localhost:8080/swagger-ui/index.html>
      path: /demo-ui.html         # Swagger UI 추가 접근 경로 => <http://localhost:8080/demo-ui.html>
      tags-sorter: alpha          # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
      operations-sorter: alpha    # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬


  datasource:
    url: jdbc:mysql://localhost:3306/insurance?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver  # 드라이버 클래스 이름 명시

  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 스키마 자동 생성 전략
    show-sql: true      # 실행되는 SQL 쿼리 출력 여부

  jwt:
    access: Qw3rTy!1@#$56789abcdefghijKLMNOP
    refresh: A1b2C3d4E5f6G7h8I9j0KLMNOPqrstuv
    accesstime: 86400 # 24시간
    refreshtime: 86400 # 24시간

  redis:


  data:
    redis:
      uri: redis://localhost:6379 # Redis URI 형식으로 설정
      timeout: 2000ms              # 연결 타임아웃
      password: yourpassword
      jedis:
        pool:
          max-active: 10            # 최대 연결 수
          max-idle: 5               # 최대 유휴 연결 수
          min-idle: 1                # 최소 유휴 연결 수