spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurance?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 스키마 자동 생성 전략
    show-sql: true      # 실행되는 SQL 쿼리 출력 여부

  jwt:
    access: Qw3rTy!1@#$56789abcdefghijKLMNOP
    refresh: A1b2C3d4E5f6G7h8I9j0KLMNOPqrstuv
    accesstime: 3600 # 1시간
    refreshtime: 86400 # 24시간

  redis:


  data:
    redis:
      uri: redis://localhost:6379 # Redis URI 형식으로 설정
      timeout: 2000ms              # 연결 타임아웃
      password: yourpassword
      jedis:
        pool:
          max-active: 10            # 최대 연결 수
          max-idle: 5               # 최대 유휴 연결 수
          min-idle: 1                # 최소 유휴 연결 수